### ISSUE TITLE
NPE after executing query which contains whitespaces

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jo-source/jo-widgets#39]
```
What steps will reproduce the problem?
1. Open search
2. Pass following string " *" - whitespace is required


What is the expected output? What do you see instead?

java.lang.NullPointerException
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createContainsAnyPredicate(CriteriaQueryCreator.java:633)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createArithmeticFilterPredicate(CriteriaQueryCreator.java:444)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createArithmeticFilterPredicate(CriteriaQueryCreator.java:301)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createFilterPredicate(CriteriaQueryCreator.java:226)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createBooleanFilterPredicate(CriteriaQueryCreator.java:282)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createFilterPredicate(CriteriaQueryCreator.java:234)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createBooleanFilterPredicate(CriteriaQueryCreator.java:282)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createFilterPredicate(CriteriaQueryCreator.java:234)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createBooleanFilterPredicate(CriteriaQueryCreator.java:282)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createFilterPredicate(CriteriaQueryCreator.java:234)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.fillQuery(CriteriaQueryCreator.java:202)
	at org.jowidgets.cap.service.jpa.impl.query.CriteriaQueryCreator.createReadQuery(CriteriaQueryCreator.java:131)
	at org.jowidgets.cap.service.jpa.impl.SyncJpaReaderServiceImpl.read(SyncJpaReaderServiceImpl.java:71)
	at org.jowidgets.cap.service.impl.ReaderServiceAdapter.read(ReaderServiceAdapter.java:61)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jowidgets.cap.service.hibernate.impl.CancelServicesDecoratorProviderImpl$CancelableInvoker.invoke(CancelServicesDecoratorProviderImpl.java:201)
	at org.jowidgets.cap.service.hibernate.impl.CancelServicesDecoratorProviderImpl$CancelableInvoker.access$300(CancelServicesDecoratorProviderImpl.java:139)
	at org.jowidgets.cap.service.hibernate.impl.CancelServicesDecoratorProviderImpl$CancelInvocationHandler.invokeAsyncSignature(CancelServicesDecoratorProviderImpl.java:134)
	at org.jowidgets.cap.common.tools.proxy.AbstractCapServiceInvocationHandler.invoke(AbstractCapServiceInvocationHandler.java:60)
	at com.sun.proxy.$Proxy21.read(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jowidgets.cap.service.jpa.impl.JpaServicesDecoratorProviderImpl$JpaInvocationHandler.invokeAsyncSignature(JpaServicesDecoratorProviderImpl.java:236)
	at org.jowidgets.cap.common.tools.proxy.AbstractCapServiceInvocationHandler.invoke(AbstractCapServiceInvocationHandler.java:60)
	at com.sun.proxy.$Proxy21.read(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jowidgets.cap.remoting.server.GenericRemoteMethod.invokeMethodOnService(GenericRemoteMethod.java:172)
	at org.jowidgets.cap.remoting.server.GenericRemoteMethod.invoke(GenericRemoteMethod.java:68)
	at org.jowidgets.cap.remoting.server.GenericRemoteMethod.invoke(GenericRemoteMethod.java:47)
	at org.jowidgets.invocation.service.server.impl.MethodImpl.invoke(MethodImpl.java:104)
	at org.jowidgets.invocation.server.impl.InvocationServerServiceRegistryImpl.onMethodInvocation(InvocationServerServiceRegistryImpl.java:75)
	at org.jowidgets.invocation.server.impl.InvocationServerMessageReceiver.onMessage(InvocationServerMessageReceiver.java:69)
	at org.jowidgets.message.impl.http.server.Connection.doRun(Connection.java:75)
	at org.jowidgets.message.impl.http.server.Connection.doRun(Connection.java:80)
	at org.jowidgets.message.impl.http.server.Connection.doRun(Connection.java:80)
	at org.jowidgets.message.impl.http.server.Connection.access$000(Connection.java:44)
	at org.jowidgets.message.impl.http.server.Connection$1.run(Connection.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)




What version of the product are you using? On what operating system?

OS: Windows 
<jowidgets.version>0.28.3</jowidgets.version>
<jocap.version>0.25.2</jocap.version>

Please provide any additional information below.


```

Original issue reported on code.google.com by `martin.k...@googlemail.com` on 5 Sep 2014 at 7:16

**Comment by herrgrossmann** [comment]
Moved to jo-client-platform issues: https://github.com/jo-source/jo-client-platform/issues/38
