### ISSUE TITLE
NatTable based table breaks with ArrayIndexOutOfBounds when reordering and hiding columns

### ISSUE THREAD

**Issue by NielsBeuck** [jo-source/jo-widgets#75]
When hiding a column in a NatTable based table, an ArrayIndexOutOfBoundsException may occur (see below). As a result, the table is not displayed correctly - columns are msising and no data is shown.

"Error while painting table
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.jowidgets.impl.widgets.basic.TableModelSpiAdapter.getColumn(TableModelSpiAdapter.java:219) ~[?:?]
	at org.jowidgets.impl.widgets.basic.TableModelSpiAdapter.getColumn(TableModelSpiAdapter.java:48) ~[?:?]
	at org.jowidgets.nattable.impl.plugin.layer.DefaultColumnDataProvider.getDataValue(DefaultColumnDataProvider.java:46) ~[?:?]
	at org.eclipse.nebula.widgets.nattable.layer.DataLayer.getDataValue(DataLayer.java:162) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.layer.DataLayer.getDataValueByPosition(DataLayer.java:442) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.grid.layer.DimensionallyDependentLayer.getDataValueByPosition(DimensionallyDependentLayer.java:386) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.grid.layer.ColumnHeaderLayer.getDataValueByPosition(ColumnHeaderLayer.java:255) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.layer.AbstractLayerTransform.getDataValueByPosition(AbstractLayerTransform.java:351) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.layer.CompositeLayer.getDataValueByPosition(CompositeLayer.java:602) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.layer.cell.AbstractLayerCell.getDataValue(AbstractLayerCell.java:64) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.jowidgets.nattable.impl.plugin.painter.AbstractJoTextPainter.getPreferredWidth(AbstractJoTextPainter.java:58) ~[?:?]
	at org.jowidgets.nattable.impl.plugin.painter.JoIconAndTextCellPainter.getPreferredWidth(JoIconAndTextCellPainter.java:59) ~[?:?]
	at org.eclipse.nebula.widgets.nattable.painter.cell.CellPainterWrapper.getPreferredWidth(CellPainterWrapper.java:56) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.jowidgets.nattable.impl.plugin.painter.AbstractJoHorizontalAlignmentPainter.paintCell(AbstractJoHorizontalAlignmentPainter.java:54) ~[?:?]
	at org.eclipse.nebula.widgets.nattable.painter.cell.CellPainterWrapper.paintCell(CellPainterWrapper.java:67) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.painter.cell.decorator.PaddingDecorator.paintCell(PaddingDecorator.java:196) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.painter.cell.CellPainterWrapper.paintCell(CellPainterWrapper.java:67) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.jowidgets.nattable.impl.plugin.painter.JoMoveOnMouseClickPaintDecorator.paintCell(JoMoveOnMouseClickPaintDecorator.java:67) ~[?:?]
	at org.eclipse.nebula.widgets.nattable.painter.cell.CellPainterWrapper.paintCell(CellPainterWrapper.java:67) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.jowidgets.nattable.impl.plugin.painter.JoColumnBackgroundPainter.paintCell(JoColumnBackgroundPainter.java:85) ~[?:?]
	at org.eclipse.nebula.widgets.nattable.painter.layer.CellLayerPainter.paintCell(CellLayerPainter.java:216) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.painter.layer.CellLayerPainter.paintLayer(CellLayerPainter.java:86) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.painter.layer.GridLineCellLayerPainter.paintLayer(GridLineCellLayerPainter.java:137) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.layer.CompositeLayer$CompositeLayerPainter.paintLayer(CompositeLayer.java:1040) ~[org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.painter.layer.NatLayerPainter.paintLayer(NatLayerPainter.java:54) [org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.NatTable.paintNatTable(NatTable.java:466) [org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.nebula.widgets.nattable.NatTable.paintControl(NatTable.java:461) [org.eclipse.nebula.widgets.nattable.core_1.4.0.201606011907.jar:?]
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:223) [org.eclipse.swt.win32.win32.x86_64_3.6.2.v3659c.jar:?]
[...]
"

**Comment by herrgrossmann** [comment]
Fix available with 0.74.0
